---
# hosts.yml

# all:
#   hosts:
#     webserver01:
#       ansible_host: 192.168.178.100
#     webserver02:
#       ansible_host: 192.168.178.101
#     dbserver01:
#       ansible_host: 192.168.178.102
#     appserver01:
#       ansible_host: 192.168.178.103

all:
  children:
    webservers:
      hosts:
        webserver01:
          ansible_host: 192.168.178.100
        webserver02:
          ansible_host: 192.168.178.101
      vars:
        web_server_type: nginx  # Beispiel-Variable für alle Webserver

    databases:
      hosts:
        dbserver01:
          ansible_host: 192.168.178.102
      vars:
        db_type: mysql  # Beispiel-Variable für alle Datenbankserver

    application_servers:
      hosts:
        appserver01:
          ansible_host: 192.168.178.103
      vars:
        app_type: django  # Beispiel-Variable für alle Applikationsserver

    special_servers:  # Falls ein Server spezielle Konfiguration benötigt
      hosts:
        dbserver01:  # Beispiel: dbserver01 bekommt eine Spezialkonfiguration
      vars:
        special_config: true
