---
# requirements.yml

roles:
  # Rollen aus Ansible Galaxy
  - name: geerlingguy.nginx
    version: 3.1.0  # Spezifische Version
  - name: geerlingguy.mysql
    version: 2.0.0

  # Eigene Rolle aus einem GitHub-Repository
  - name: my_custom_role
    src: git+https://github.com/meinuser/mein_ansible_repo.git
    version: main  # Oder ein spezifischer Branch/Tag
    scm: git

  # Rolle aus einem privaten GitHub-Repository mit SSH-Zugang
  - name: private_role
    src: git+ssh://git@github.com/meinuser/private_ansible_role.git
    version: develop
    scm: git

collections:
  # Ansible Collections von Galaxy
  - name: community.general
    version: 5.3.0
  - name: community.docker
    version: 3.4.0

  # Collection direkt aus einem GitHub-Repository
  - name: my_custom_collection
    type: git
    source: https://github.com/meinuser/meine_ansible_collection.git
    version: v1.0.0
