---
# site.yml

- name: Configure Web Servers
  hosts: webservers
  roles:
    - web_role

- name: Configure Database Servers
  hosts: databases
  roles:
    - db_role

- name: Configure Application Servers
  hosts: application_servers
  roles:
    - app_role

- name: Apply Special Configuration
  hosts: special_servers
  roles:
    - special_role
